import { Geist, Geist_Mono } from "next/font/google";
import MenuBar from "@/app/components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="m-50">
        {/* Header & nav bar */}
        <MenuBar />
        <hr />
        {/* Page content */}
        {children}
        {/* Footer */}
        <hr />
        <footer>
          <h2>Footer</h2>
        </footer>
      </body>
    </html>
  );
}
